spring.application.name=WebappMI

#spring.datasource.jdbc-url=jdbc:sqlserver://sql-server-saurav-az.database.windows.net:1433;databaseName=sql-db-saurav-az;encrypt=true;authentication=ActiveDirectoryManagedIdentity;msiClientId=2f571c59-ca45-42dc-859c-27139978b654
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.security.oauth2.resourceserver.jwt.issuer-uri = https://login.microsoftonline.com/f40262c3-5794-45b5-8fbd-bcdba3b6cfec/v2.0



# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
msiClientId=2f571c59-ca45-42dc-859c-27139978b654
spring.main.lazy-initialization=true

# Datasource Configuration

# Logging Configuration
logging.level.com.yourcompany=DEBUG
logging.level.com.microsoft.sqlserver=WARN
logging.level.com.azure.identity=INFO