spring.application.name=WebappMI

spring.datasource.jdbc-url=jdbc:sqlserver://sql-server-saurav-az.database.windows.net:1433;databaseName=sql-db-saurav-az;encrypt=true;authentication=ActiveDirectoryManagedIdentity;msiClientId=2f571c59-ca45-42dc-859c-27139978b654
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.profiles.active=local
